luck_numbers = [4, 8, 15, 16, 23, 42]
friends = ["Tom", "Sally", "Jerry", "Oscar", "Serena"]
print(friends)
friends.sort()
print(friends)
print(friends[0])
print(friends[2])
print(friends[-1])
print(friends[1:])
print(friends[1:3])
friends[1] = "Mary"
print(friends)
friends.append("Donald")
print(friends)
friends.extend(luck_numbers)
print(friends)
friends.insert(2, "Barake")
print(friends)
friends.remove("Donald")
print(friends)
friends.pop()
print(friends)
friends.pop(6)
print(friends)
print(friends.index("Mary"))
friends.insert(3, "Mary")
print(friends)
print(friends.count("Mary"))
friends.clear()
print(friends)
print(luck_numbers)
luck_numbers_2 = luck_numbers.copy()
luck_numbers.reverse()
print(luck_numbers)
print(luck_numbers_2)